import DeliveriesInfo from "../interfaces/types/DeliveriesInfo";
import RoutedDeliveryList from "../interfaces/RoutedDeliveryList";

/* Function to assign the address and hawb value from the
delivery list to the routed delivery list generated by
the VROOM Express API */
const formatRoutedDeliveryList = (
  routedDeliveryList: RoutedDeliveryList,
  deliveriesInfo: DeliveriesInfo
) => {
  return routedDeliveryList.routes.map((route) => {
    /* Removing the start and end from the steps */
    route.steps.shift();
    route.steps.pop();

    const steps = route.steps.map((step) => {
      const correspondingDelivery = deliveriesInfo.find(
        (delivery) => delivery.id === step.job
      )!;

      return {
        ...step,
        ...correspondingDelivery,
      };
    });

    return { ...route, steps };
  });
};

export default formatRoutedDeliveryList;
